#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace WeaponsFactory.MySql.DataAccess	
{
	public partial class Sale
	{
		private int _saleId;
		public virtual int SaleId
		{
			get
			{
				return this._saleId;
			}
			set
			{
				this._saleId = value;
			}
		}
		
		private int _weaponId;
		public virtual int WeaponId
		{
			get
			{
				return this._weaponId;
			}
			set
			{
				this._weaponId = value;
			}
		}
		
		private string _weaponName;
		public virtual string WeaponName
		{
			get
			{
				return this._weaponName;
			}
			set
			{
				this._weaponName = value;
			}
		}
		
		private string _vendorName;
		public virtual string VendorName
		{
			get
			{
				return this._vendorName;
			}
			set
			{
				this._vendorName = value;
			}
		}
		
		private int _quantity;
		public virtual int Quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		
		private decimal _income;
		public virtual decimal Income
		{
			get
			{
				return this._income;
			}
			set
			{
				this._income = value;
			}
		}
		
	}
}
#pragma warning restore 1591
